version: '3.3'

services:
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pubsub
        ports:
            - "3307:3306"
    pub-sub-emulator:
        image: google/cloud-sdk:latest
        command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085", "--project=test"]
        ports:
        - "8085:8085"